version: '3.4'

services:
    nginx:
        # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#customization
        image: webdevops/php-nginx-dev:8.2
        volumes:
            - ./app:/app
            - ./.docker/nginx/conf.d/default.conf:/opt/docker/etc/nginx/vhost.conf
        working_dir: /app
        environment:
            # PHP config
            # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#environment-variables
            PHP_DATE_TIMEZONE: "Europe/Paris"
            PHP_DISPLAY_ERRORS: "on"
            PHP_MAX_EXECUTION_TIME: 7200
            PHP_OPCACHE_REVALIDATE_FREQ: 0
            php.xdebug.var_display_max_depth: 10
            php.xdebug.var_display_max_data: 2048
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.yc_season.loadbalancer.server.port=80

                - traefik.http.routers.yc_season.rule=Host(`yc-season.local.barlito.fr`)
                - traefik.http.routers.yc_season.entrypoints=http
                #- traefik.http.routers.yc_season.middlewares=tls-redirectscheme

                - traefik.http.routers.yc_season-secure.rule=Host(`yc-season.local.barlito.fr`)
                - traefik.http.routers.yc_season-secure.entrypoints=https
                - traefik.http.routers.yc_season-secure.tls=true
        networks:
            - yc_season_internal
            - traefik_traefik_proxy

    db:
        image: postgres:15
        environment:
            POSTGRES_PASSWORD: root
        volumes:
            - yc_season_db_data:/var/lib/postgresql/data:rw
        networks:
            - yc_season_internal

    adminer:
        image: adminer
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.yc-season-adminer.loadbalancer.server.port=8080

                - traefik.http.routers.yc-season-adminer.rule=Host(`yc-season-adminer.local.barlito.fr`)
                - traefik.http.routers.yc-season-adminer.entrypoints=http

                - traefik.http.routers.yc-season-adminer-secure.rule=Host(`yc-season-adminer.local.barlito.fr`)
                - traefik.http.routers.yc-season-adminer-secure.entrypoints=https
                - traefik.http.routers.yc-season-adminer-secure.tls=true
        networks:
            - yc_season_internal
            - traefik_traefik_proxy

volumes:
    yc_season_db_data:

networks:
    traefik_traefik_proxy:
        external: true
    yc_season_internal:
        driver: overlay
