services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Barlito\Utils\Behat\:
        resource: '../vendor/barlito/utils/src/Behat/*'

#    App\Tests\Functional\:
#        resource: '../tests/Functional/*'
#
#    App\Tests\Unit\:
#        resource: '../tests/Unit/*'

    # Services
    Barlito\Utils\Behat\Component\EntityManagerContext:
        $entityNamespace: App\Entity

    Barlito\Utils\Behat\Mock\LoggerMock:
        decorates: Psr\Log\LoggerInterface
        arguments:
            - '@Barlito\Utils\Behat\Mock\LoggerMock.inner'
