services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Functional\:
        resource: '../tests/Functional/*'

    App\Tests\Unit\:
        resource: '../tests/Unit/*'

    # Services

    App\Tests\Behat\EntityManagerContext:
        $entityNamespace: App\Entity
