name: Starter workflow

on: push

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  init_symfony_starter:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Deploy stack
        run: make docker.deploy.ci

#     Dry run only to avoid action to fail because of Symfony fresh files
      - name: Run php cs fixer
        run: make cs_fixer

      - name: Run php cs
        run: make phpcs

      - name: Run phpmd
        run: make phpmd

      - name: Run phpunit
        run: make phpunit

      - name: Run behat
        run: make behat

      - name: Undeploy stack
        run: make docker.undeploy.ci

